### ISSUE TITLE
Meta workplan for Summer Project

### ISSUE THREAD

**Issue by marc-hanheide** [pet1330/FInCoR#24]
- [ ] 1. #21 is an individual task you can work on without touching any of the others
- [x] 2. #17 and #22 are similar. It's about setting up and calibrating a proper setup at Baxter
- [x] 3. once #17 and #22 are done, you can work on #18
- [ ] 4. With the above, you should be able to complete #19

This completes the first important, as we should now be able to put objects in the scene, and call the action servers using `rosrun actionlib axclient.py` and see the robot doing things!
#20 is the next step which should be working already with @cdondrup's implementation
